apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards
  namespace: monitoring
  labels:
    grafana_dashboard: "1"
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: monitoring
    app.kubernetes.io/component: dashboards
  annotations:
    kubernetes.io/description: Unified Cluster Enterprise Overview dashboard provisioning

data:
  cluster-enterprise-overview.json: |
    ${DASHBOARD_JSON}
