apiVersion: v1
kind: ConfigMap
metadata:
  name: elasticsearch-ilm-policy
  namespace: logging
data:
  k3s-logs-policy.json: |
    {
      "policy": {
        "phases": {
          "hot": {
            "actions": {
              "rollover": {
                "max_size": "3gb",
                "max_age": "1d",
                "max_docs": 50000000
              },
              "set_priority": {
                "priority": 100
              }
            }
          },
          "warm": {
            "min_age": "3d",
            "actions": {
              "set_priority": {
                "priority": 50
              },
              "allocate": {
                "number_of_replicas": 0
              },
              "forcemerge": {
                "max_num_segments": 1
              },
              "readonly": {},
              "shrink": {
                "number_of_shards": 1
              }
            }
          },
          "cold": {
            "min_age": "10d",
            "actions": {
              "set_priority": {
                "priority": 0
              },
              "freeze": {}
            }
          },
          "delete": {
            "min_age": "15d",
            "actions": {
              "delete": {}
            }
          }
        }
      }
    }
  
  k3s-logs-filebeat-policy.json: |
    {
      "policy": {
        "phases": {
          "hot": {
            "actions": {
              "rollover": {
                "max_size": "2gb",
                "max_age": "1d"
              },
              "set_priority": {
                "priority": 90
              }
            }
          },
          "warm": {
            "min_age": "2d",
            "actions": {
              "set_priority": {
                "priority": 40
              },
              "forcemerge": {
                "max_num_segments": 1
              },
              "readonly": {}
            }
          },
          "cold": {
            "min_age": "7d", 
            "actions": {
              "set_priority": {
                "priority": 0
              },
              "freeze": {}
            }
          },
          "delete": {
            "min_age": "12d",
            "actions": {
              "delete": {}
            }
          }
        }
      }
    }